services:
  api:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - my-network
    # environment:
    #   - OLLAMA_BASE_URL=http://ollama:11434
    # depends_on:
    #   - ollama

  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama
  #   restart: unless-stopped
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama:/root/.ollama
  #   networks:
  #     - ollama-network
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]
    

# volumes:
#   ollama:
    
  # ollama:
  #   image: ollama/ollama:latest
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   networks:
  #     - ollama-network
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   command: ["ollama", "serve"]

# volumes:
#   ollama_data:

networks:
  my-network:
    driver: bridge



